//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace nhom6
{
    using System;
    using System.Collections.Generic;
    
    public partial class ColorImage
    {
        public int ProductID { get; set; }
        public int ColorID { get; set; }
        public string Image { get; set; }
    
        public virtual Color Color { get; set; }
        public virtual Product Product { get; set; }
    }
}
